
colorscheme torte

set backupdir="%HOME%/vimfiles/backup"
set directory="%HOME%/vimfiles/backup"

set tabstop=4
set shiftwidth=4
set softtabstop=4

execute pathogen#infect()

syntax on
filetype plugin indent on

