
colorscheme torte

set backupdir="%VIM_HOME%/backup"
set directory="%VIM_HOME%/backup"

set tabstop=4
set shiftwidth=4
set softtabstop=4

execute pathogen#infect()

syntax on
filetype plugin indent on

