# Bash config

# Export vars
#PS1='\n\w\n>'
#color_prompt=yes

# HOME vars
# None yet

# PATH vars
export PATH="${PATH}:/c/Windows/System32/config/systemprofile/AppData/Local/Programs/Python/Python37/Scripts"

# Aliases
alias dir='ls -la'
alias cls='clear'
alias home='cd ~'

[[ $- = *i* ]] && source ~/bashrc.d/liquidprompt/liquidprompt

